### ISSUE TITLE
A few thoughts on the presentation (feel free to ignore)

### ISSUE THREAD

**Issue by vincentarelbundock** [ess-intro/presentation-org-mode#3]
Hi,

I exchanged a couple messages with @eddelbuettel who pointed me to this project. Looks fantastic! Thanks for your work on this!

I made the transition from a vim+tmux workflow to emacs for R development about 3 weeks ago. I'm also very interested in org-mode for TODO and calendaring. So I guess I'm pretty close to your target audience.

I learned a lot by browsing your repo, and figured I'd write down a few thoughts which crossed my mind while reading. A lot of these things relate to org-mode itself, and not to your repo specifically. They're just reactions from a new user, so you should obviously feel free to ignore them entirely.

The code block "pop-out" mechanism is still not very intuitive to me. I expected to edit the org file and for ESS bindings to kick in automatically whenever my cursor is inside an R block (with `C-RET` sending stuff to a console, etc.). Is that possible at all, or is the `C-c '` mechanism really my best bet?

Initially, I couldn't get the code block completion that you emphasize with shortcuts like: `[<X][tab]`. After some googling, I found [this link](https://github.com/syl20bnr/spacemacs/issues/11798) which suggests that this expansion mechanism was disabled in org-mode 9.2, and that the new idiomatic way of doing things is to call: `C-c C-,`  (There's also a reddit thread somewhere.) For me, this makes a which-key-style menu pop-up with block types. If that's really the "new way", it might be best to emphasize that instead, or at least to explain how to re-enable the "old" one.

Tangling code and asking one block to evaluate another seem like advanced features. Now that I know that these things exist, I will certainly find a use for them, but I have worked with Rmarkdown notebooks *a lot* and never really had the spontaneous desire to do this. So i'm not convinced this should be up at the front of a 5 minute intro presentation.

I like the section about tables a lot, but one very common task that I think a lot of newbies like me might struggling with, is how to export tables produced by an `R` package. For example, I maintain the [`modelsummary` package](https://vincentarelbundock.github.io/modelsummary/index.html) which can be used to produce regression tables in various formats. It took me a while to figure out how to get the output to display properly in HTML or PDF. I eventually settled on this, but to be honest, I'm still not exactly sure why it works:

````
#+begin_src R :exports both :results output latex
library(modelsummary)

mod <- lm(hp ~ mpg, data = mtcars)

modelsummary(mod, output = "latex")
#+end_src
````

I feel that presenting tables created in programmatic fashion is one of the main tasks for stats notebooks like this. After all, the main reason why we use notebooks is because we need to produce a "deliverable" that's ready for consumption by some reader. And pretty tables are almost always a part of that.

Relatedly, I'm still not exactly sure what to do for graphs. I have some code I cut and paste depending on `ggplot2` vs base `R` plots, but I'm not sure exactly why that code works. And why do I have to specify the file name every time? That's annoying!

Anyway, these are just a few thoughts I had. I'm grateful for your work on this, and happy that some people are still bucking the trend of IDE hegemony.

**Comment by greg-minshall** [comment]
@vincentarelbundock thanks very much!

amusingly, only a few days ago did i discover `C-c C-,`.  i will convert the documentation to use that.  i didn't realize `[s[tab]` was no longer valid; somehow i've kept it alive.

it will take me a while to go through your very informative message.  thanks much for that!

by the way, your code example.  does the following work for you?
````
#+begin_src R :exports both :colnames yes
library(modelsummary)

mod <- lm(hp ~ mpg, data = mtcars)

modelsummary(mod, output = "data.frame")
#+end_src
````

more later.  again (and again, ...), thanks!

**Comment by vincentarelbundock** [comment]
Fantastic!

Oh, the data.frame output is super nice; I didn't know that, thanks.

In this particular application, the `output=data.frame` actually gives us a bunch of extraneous information, but that's really a package specific issue related to `modelsummary`. Printing a subset of this data.frame would work well in this application.

But if we complicate matters a bit, we run into issues. For example, what if I want to include significance stars with a footnote? Or a title? Or some color?

To illustrate, this org-mode document uses the `modelsummary` and `kableExtra` packages to create the complicated table in the screenshot below:

````
#+latex_header_extra: \usepackage{colortbl,xcolor}

#+begin_src R :exports both :results output latex
  library(modelsummary)
  library(kableExtra)

  mod <- list(
    lm(hp ~ mpg, data = mtcars),
    lm(hp ~ mpg + drat, data = mtcars))

  modelsummary(mod,
               output = "latex",
               title = "A complicated example.",
               stars = TRUE) %>%
    row_spec(2, background = "pink") %>%
    add_header_above(c(" " = 1, "Two strategies" = 2))
#+end_src
````

<img width="426" alt="Screen Shot 2021-04-05 at 23 03 09" src="https://user-images.githubusercontent.com/987057/113653108-316ba900-9663-11eb-9c59-05e40de4fcc7.png">

**Comment by greg-minshall** [comment]
Vincent, good, i'm glad that at least minimally works.  i was going to say, if you are trying to have very fine control over your output (more than just a table, with more-or-less default export options), then probably you *will* want to use your latex exporter, the way you originally suggested.

the downside of doing that is then you limit your subsequent exports, i.e., you can export to PDF, but not to HTML.  (though, of course, with sufficient programming... :)

**Comment by vincentarelbundock** [comment]
Exactly right.

The neat thing is that I can use a `:var` to dynamically change the `output` argument for different export formats based on `org-export-current-backend`. 

But as you say, I'm trying to get pretty fine control, so this is almost certainly out of scope for the kind of video you're prepping :)

Good luck!

**Comment by greg-minshall** [comment]
Vincent,

there was this nice [example](https://orgmode.org/list/87wntjowtz.fsf@posteo.net/) recently in the org-mode e-mail list on how to condition ones behavior based on the current exporting backend.

**Comment by vincentarelbundock** [comment]
Greg,

This is thread was super useful; macros are amazing. I can just "decorate" a source block with a macro to switch the header automatically based on the backend:

````
#+PROPERTY: header-args:R :var orgbackend=(prin1-to-string org-export-current-backend)
#+MACRO: Rtable (eval (concat "#+header: :results output " (prin1-to-string org-export-current-backend)))

{{{Rtable}}}
#+begin_src R :exports both
  library(modelsummary)
  mod = lm(hp ~ mpg, data = mtcars)
  modelsummary(mod, output = orgbackend) 
#+end_src
````

Super easy. Thanks again!

**Comment by greg-minshall** [comment]
the e-mail list has a lot of good content.

**Comment by greg-minshall** [comment]
Vincent,

a few more comments on your original post.

some of the other presenters have mentioned using the "polymode" (i think) package.  whether that might give you a "more native" editing experience when editing inline in the .org buffer i don't know.  (i wasn't able to get polymode to work for me, but gave up quickly.)  other than that, yes, `[C-c ']` is your best bet.

it turns out that `[<X][tab]` works if you have `org-tempo` enabled.  you can do via
````
(customize-variable 'org-modules)
````
but, certainly, `[C-c C-,]` works well.

> Tangling code and asking one block to evaluate another seem like advanced features. Now that I know that these things exist, I will certainly find a use for them, but I have worked with Rmarkdown notebooks a lot and never really had the spontaneous desire to do this. So i'm not convinced this should be up at the front of a 5 minute intro presentation.

at least in the beamer presentation, i don't see where i have a tangle depend on an evaluation.  (though i certainly do use that feature in some code.)  it would be helpful if you could  point out where you saw that.

it's been several years since i've produced graphs and exported them via org mode.  if i look back at a recent example of a small file producing a graph, i seem to write the image from my R code, and hard code a link.  so, i can't help with that.  possibly you've figure it out already.

again, thanks for you comments.  i think i've processed them all.

**Comment by vincentarelbundock** [comment]
Oh, sorry for confusion. I was looking at the HTML reference document and not the Beamer. The slides hit all the right points, IMO. Great stuff.

For plots, I think the only nuance is that `ggplot2` graphs (probably more popular than Base R graphs by now) require us to add `output` to the `:results` section, because they are "printed". This is not the case with Base R plots, for some reason. In both cases, we need to specify a filename manually, and we need to include `:results file graphics` in the header. For example:

````
* Base R graphics

#+BEGIN_SRC R :exports results :file image1.png :results file graphics
plot(mtcars$hp, mtcars$mpg)
#+END_SRC

* ggplot2 graphics

#+BEGIN_SRC R :exports results :file image2.png :results output file graphics
library(ggplot2)
ggplot(mtcars, aes(hp, mpg)) +
  geom_point()
#+END_SRC
````

**Comment by greg-minshall** [comment]
Vincent, thanks again.  i've put in a graphics example, using base graphics, but adding the `:results output`, as it seems to do no harm there.

also, i wanted to close the loop on this:
````
Tangling code and asking one block to evaluate another seem like advanced features.
````

i wonder if you are looking at one of the `:noweb` references, maybe the one in this source block?
````
#+name: peaks-and-valleys-tangling
#+begin_src R :exports both :tangle peaks-and-valleys.el :noweb yes
  <<peaks-and-valleys>>
#+end_src
````

here, the *contents* (not the results) of the `peaks-and-valleys` code block is being inserted into the file as it is tangled (sort of like a `#include` in C).  i wasn't sure if this was clear or not.  there's no verification required.

cheers.

**Comment by vincentarelbundock** [comment]
@greg-minshall thanks for the follow up! Yes, I think I understand this now. Interesting feature.

**Comment by vincentarelbundock** [comment]
I just watched the video. Awesome work! Reading the slide deck gave me a pretty good sense of it already, but seeing it live was even better. Thanks!

**Comment by greg-minshall** [comment]
thanks!
